### ISSUE TITLE
USER STORY:  Create a Profile

### ISSUE THREAD

**Issue by fraserivison** [fraserivison/wave-app#4]
As a signed up user, I can create a profile showcasing my material, future events, and previous work so that others can see my abilities and listen to my music.

## **Acceptance Criteria**

-Given a completed registration, the user can access the profile creation page.
-When the user inputs their music, events, and previous work, the details are saved and displayed on their profile.
-Then the profile is visible to other users on the platform.

## **Tasks**

- [ ] Create a profile page that is customisable with fields for a bio, music, events, and previous work.
- [ ] Implement backend functionality to save profile data to the database.
- [ ] Display the created profile on the user’s public page.
- [ ] Test visibility of the profile for other users.
